Repository calniotrey/space-corp, pull requests merged in 2021-03, with the labels that each got.

#34 Corporate registry - edits
  common/scripted_effects/space_corps_utility_effects.txt
  events/iisc_registry_events.txt
  interface/iisc_registry_interface.gui
Labels: tweak

#37 Loc french
  localisation/french/iisc_hq_deposits_l_french.yml
  localisation/french/iisc_l_french.yml
Labels: localisation

#42 Add budget check
  common/scripted_triggers/iisc_military_triggers.txt
Labels: bug

#52 Increase trade cooldown to 90 days
  common/scripted_effects/iisc_corps_effects.txt
Labels: tweak

#54 Add a compatibility trigger
  events/iisc_start_events.txt
Labels: tweak

#55 Cleared the error.log from registry UI errors
  interface/iisc_registry_interface.gui
Labels: code maintenance

#53 Feat handle overlord disconnection
  common/on_actions/iisc_on_actions.txt
  common/scripted_effects/iisc_corps_effects.txt
  common/scripted_effects/iisc_creation_effects.txt
  common/scripted_effects/iisc_hq_deposits_effects.txt
  common/scripted_triggers/iisc_triggers.txt
  events/iisc_corps_events.txt
  events/iisc_diplomacy_events.txt
  events/iisc_pulse_events.txt
  events/iisc_registry_events.txt
Labels: tweak

#59 Add dynamic budget and remove debug budget
  common/scripted_effects/iisc_builder_effects.txt
  common/scripted_effects/iisc_corps_effects.txt
  common/scripted_effects/iisc_creation_effects.txt
  common/scripted_triggers/iisc_hq_deposits_triggers.txt
  common/scripted_triggers/iisc_triggers.txt
  common/scripted_variables/iisc_scripted_variables.txt
  todo.md
Labels: tweak

#70 Remove iisc_hq flag and add dynamic corp cap
  common/scripted_effects/iisc_corps_effects.txt
  common/scripted_effects/iisc_utility_effects.txt
  common/scripted_triggers/iisc_triggers.txt
  events/iisc_pulse_events.txt
Labels: tweak
