Repository calniotrey/space-corp, pull requests merged in 2021-04, with the labels that each got.

#65 Feature modmenu
  common/button_effects/iisc_modmenu_buttons.txt
  common/edicts/iisc_edicts.txt
  common/on_actions/iisc_on_actions.txt
  common/scripted_effects/iisc_science_ship_effects.txt
  common/scripted_effects/iisc_utility_effects.txt
  common/scripted_loc/iisc_modmenu_loc.txt
  common/scripted_triggers/iisc_hq_deposits_triggers.txt
  common/scripted_triggers/iisc_triggers.txt
  events/iisc_builder_events.txt
  events/iisc_convoy_events.txt
  events/iisc_military_events.txt
  events/iisc_modmenu_events.txt
  events/iisc_science_ships_events.txt
  events/iisc_start_events.txt
  gfx/interface/buttons/iisc_button_pause.dds
  gfx/interface/buttons/iisc_button_play.dds
  gfx/interface/modmenu/modmenu_bg.dds
  gfx/interface/modmenu/sidebar.dds
  gfx/interface/modmenu/sidebar_image.dds
  gfx/interface/modmenu/sidebar_mask.dds
  interface/iisc_modmenu_interface.gfx
  interface/iisc_modmenu_interface.gui
  localisation/english/iisc_l_english.yml
Labels: feature

#73 Feature modmenu - unknown status add
  common/scripted_loc/iisc_modmenu_loc.txt
  interface/iisc_modmenu_interface.gfx
  localisation/english/iisc_l_english.yml
Labels: tweak

#74 English loc changes
  localisation/english/iisc_l_english.yml
Labels: localisation

#75 Make the registry a bit larger
  common/scripted_loc/iisc_registry_loc.txt
  gfx/interface/buttons/iisc_button_80_34_animated.dds
  interface/iisc_registry_interface.gfx
  interface/iisc_registry_interface.gui
  localisation/english/iisc_l_english.yml
  localisation/french/iisc_l_french.yml
Labels: tweak

#76 Add science ships and builders windup
  common/scripted_effects/iisc_builder_effects.txt
  common/scripted_effects/iisc_science_ship_effects.txt
  common/scripted_triggers/iisc_triggers.txt
Labels: tweak

#78 Default loc for other languages
  localisation/braz_por/iisc_hq_deposits_l_braz_por.yml
  localisation/braz_por/iisc_l_braz_por.yml
  localisation/german/iisc_hq_deposits_l_german.yml
  localisation/german/iisc_l_german.yml
  localisation/polish/iisc_hq_deposits_l_polish.yml
  localisation/polish/iisc_l_polish.yml
  localisation/russian/iisc_hq_deposits_l_russian.yml
  localisation/russian/iisc_l_russian.yml
  localisation/simp_chinese/iisc_hq_deposits_l_simp_chinese.yml
  localisation/simp_chinese/iisc_l_simp_chinese.yml
  localisation/spanish/iisc_hq_deposits_l_spanish.yml
  localisation/spanish/iisc_l_spanish.yml
Labels: localisation

#77 Fixed flag in science ship orders
  common/scripted_effects/iisc_science_ship_effects.txt
Labels: bug

#83 Added thumbnail
  descriptor.mod
  thumbnail.png
Labels: documentation

#80 Tweaks for 1.0.0
  common/scripted_effects/iisc_builder_effects.txt
  common/scripted_effects/iisc_convoy_effects.txt
  common/scripted_effects/iisc_corps_effects.txt
  common/scripted_effects/iisc_creation_effects.txt
  common/scripted_effects/iisc_military_fleet_effects.txt
  common/scripted_effects/iisc_science_ship_effects.txt
  common/scripted_triggers/iisc_triggers.txt
  common/static_modifiers/iisc_static_modifiers.txt
  events/iisc_builder_events.txt
  events/iisc_convoy_events.txt
  events/iisc_corps_events.txt
  events/iisc_military_events.txt
  events/iisc_science_ships_events.txt
Labels: tweak

#86 Tweak military ships
  common/scripted_effects/iisc_corps_effects.txt
  common/scripted_effects/iisc_military_fleet_effects.txt
  common/scripted_variables/iisc_scripted_variables.txt
  events/iisc_pulse_events.txt
Labels: feature, tweak

#87 Add missing french loc, fix ET
  localisation/french/iisc_l_french.yml
Labels: localisation

#92 Add russian and german translation.
  descriptor.mod
  localisation/german/iisc_hq_deposits_l_german.yml
  localisation/german/iisc_l_german.yml
  localisation/russian/iisc_hq_deposits_l_russian.yml
  localisation/russian/iisc_l_russian.yml
  steam_description.txt
Labels: localisation

#94 Increased cost by 50%
  common/scripted_variables/iisc_scripted_variables.txt
Labels: tweak

#96 Prevent corp survey of precursor systems
  common/scripted_effects/iisc_science_ship_effects.txt
Labels: tweak

#97 Add a check on hull sizes tech
  common/scripted_effects/iisc_military_fleet_effects.txt
Labels: bug

#98 Add lost cohesion to the federation
  common/scripted_effects/iisc_creation_effects.txt
  events/iisc_corps_events.txt
Labels: bug

#99 Add changelog file
  changelog.txt
Labels: documentation

#100 Purge error.log
  common/country_types/iisc_country_types.txt
  common/governments/authorities/iisc_authorities.txt
  common/on_actions/iisc_on_actions.txt
  common/scripted_effects/iisc_corps_effects.txt
  common/scripted_effects/iisc_creation_effects.txt
  common/scripted_effects/iisc_give_society_effects.txt
  common/scripted_effects/iisc_leader_effects.txt
  common/scripted_effects/iisc_military_fleet_effects.txt
  common/scripted_effects/iisc_science_ship_effects.txt
  common/scripted_effects/iisc_utility_effects.txt
  common/scripted_triggers/iisc_military_triggers.txt
  common/ship_sizes/iisc_ship_sizes.txt
  common/subjects/iisc_subjects.txt
  descriptor.mod
  localisation/german/iisc_l_german.yml
Labels: bug

#102 Add changelog, adapt description and descriptor
  changelog.txt
  descriptor.mod
  steam_description.txt
Labels: documentation

#103 Fix attack loop when changing corp overlord
  common/scripted_effects/iisc_military_fleet_effects.txt
Labels: bug

#104 Disable edict when dmm installed
  common/edicts/iisc_edicts.txt
Labels: bug

#105 Feat 1.1.1
  changelog.txt
  common/deposits/iisc_income_deposits.txt
  common/economic_categories/iisc_economic_categories.txt
  common/scripted_effects/iisc_builder_effects.txt
  common/scripted_effects/iisc_corps_effects.txt
  common/scripted_effects/iisc_creation_effects.txt
  common/scripted_effects/iisc_hq_deposits_effects.txt
  common/scripted_effects/iisc_leader_effects.txt
  common/scripted_effects/iisc_utility_effects.txt
  common/scripted_triggers/iisc_triggers.txt
  common/scripted_variables/iisc_scripted_variables.txt
  events/iisc_corps_events.txt
  localisation/braz_por/iisc_l_braz_por.yml
  localisation/english/iisc_l_english.yml
  localisation/french/iisc_l_french.yml
  localisation/german/iisc_l_german.yml
  localisation/polish/iisc_l_polish.yml
  localisation/russian/iisc_l_russian.yml
  localisation/simp_chinese/iisc_l_simp_chinese.yml
  localisation/spanish/iisc_l_spanish.yml
Labels: tweak
